/*
 * Copyright 2026 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

use std::fmt::Display;
use std::fmt::Formatter;

use providers::UnpackProvider;
use starlark::values::FrozenHeapRef;
use starlark::values::FrozenValueTyped;

use crate::attr::Attr;
use crate::ffi;
use crate::rule::FrozenRule;
use crate::File;
use crate::LabelRef;
use crate::PackageRef;
use crate::StarlarkSession;

/// Represents a GN target, wrapping a C++ `Target` pointer and adding Starlark-specific attributes and providers.
#[derive(allocative::Allocative)]
pub struct Target {
    #[allocative(skip)]
    cxx: &'static ffi::Target,
    /// Set for targets generated by starlark only.
    #[allocative(skip)]
    rule: Option<FrozenValueTyped<'static, FrozenRule>>,
    /// The order of these fields is the same as rule.attrs_record_type
    pub(crate) attrs: Vec<Attr>,
    providers: providers::TargetProviders,
    pub(crate) phonies: Vec<(File, Vec<File>)>,
}

unsafe impl Send for Target {}
unsafe impl Sync for Target {}

impl Target {
    /// Creates a new `Target` generated by a Starlark custom rule.
    pub fn new_starlark(
        cxx: &'static ffi::Target,
        rule: FrozenValueTyped<'static, FrozenRule>,
        attrs: Vec<Attr>,
    ) -> Self {
        Self {
            cxx,
            rule: Some(rule),
            attrs,
            providers: Default::default(),
            phonies: Vec::new(),
        }
    }

    /// Creates a new `Target` wrapping a native C++ GN target (no rule extensions).
    pub fn new_cxx(cxx: &'static ffi::Target, session: &StarlarkSession) -> Self {
        let outputs = cxx.output_files();
        let builtins = session.builtins();
        let providers = providers::TargetProviders::new_cxx(outputs, builtins);

        Self {
            cxx,
            rule: None,
            attrs: Vec::new(),
            providers,
            phonies: Vec::new(),
        }
    }

    pub(crate) fn providers(&self) -> &providers::TargetProviders {
        &self.providers
    }

    /// Computes the output directory path for the target.
    pub fn target_out_dir(&self, before: &str, between: &str, separator: &str) -> String {
        let label = self.label();
        let toolchain = self.toolchain();

        let mut path = String::new();
        path.push_str(before);
        if toolchain != self.default_toolchain() {
            path.push_str(toolchain.name);
            path.push_str("/");
        }
        path.push_str(between);
        let pkg = label.package.as_str();
        if pkg.len() > 2 {
            path.push_str(&pkg[1..]);
        }
        path.push_str(separator);
        path.push_str(label.name);
        path
    }

    /// Declares a new output file under the target's output directory.
    pub fn declare_file(&self, suffix: &str) -> File {
        let mut path = self.target_out_dir("", "obj/", "/");
        path.push('/');
        path.push_str(suffix);
        File::from_rust(path)
    }

    /// Returns the target's package.
    pub fn package<'a>(&'a self) -> &'a PackageRef {
        self.label().package
    }

    /// Returns the target's label.
    pub fn label<'a>(&'a self) -> LabelRef<'a> {
        self.cxx.label()
    }

    /// Returns the target's toolchain label.
    pub fn toolchain<'a>(&'a self) -> LabelRef<'a> {
        self.cxx.toolchain_label()
    }

    /// Returns the default toolchain label.
    pub fn default_toolchain<'a>(&'a self) -> LabelRef<'a> {
        self.cxx.default_toolchain_label()
    }

    /// Returns the outputs generated by this target.
    pub fn outputs(&self) -> Vec<File> {
        if !self.providers.output_files().is_empty() {
            self.providers.output_files().to_vec()
        } else {
            self.cxx.output_files()
        }
    }

    pub(crate) fn ptr(&self) -> *mut ffi::Target {
        self.cxx as *const ffi::Target as *mut ffi::Target
    }

    pub(crate) fn configure_cxx_target(&self) {
        self.cxx.set_starlark_target(self);
    }

    pub(crate) fn rule(&self) -> Option<FrozenValueTyped<'static, FrozenRule>> {
        self.rule.clone()
    }

    pub(crate) fn get_unevaluated_attrs(&self) -> impl Iterator<Item=(&str, &Attr)> {
        std::iter::zip(
            self.rule.as_ref().unwrap().attrs.keys().map(|s: &String| s.as_str()),
            &self.attrs,
        )
    }

    pub(crate) fn set_providers(
        &mut self,
        heap: &FrozenHeapRef,
        providers: &[UnpackProvider],
        builtins: &providers::BuiltinModule,
    ) -> starlark::Result<()> {
        self.providers = providers::TargetProviders::new(heap.clone(), providers, builtins)?;
        Ok(())
    }
}

impl std::fmt::Debug for Target {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Target({})", self.label())
    }
}

impl Display for Target {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.label())?;
        let toolchain = self.toolchain();
        if toolchain != self.default_toolchain() {
            write!(f, "({toolchain})")?;
        }
        Ok(())
    }
}


