use std::collections::hash_map::HashMap;
use std::path::PathBuf;
use std::pin::Pin;
use std::sync::RwLock;

use starlark::environment::FrozenModule;
use starlark::environment::Globals;
use starlark::syntax::Dialect;

use crate::ffi;
use crate::session::evaluator::{EvalContext, EvalKind};
use crate::session::globals;
use crate::File;
use crate::Label;
use crate::LabelRef;
use crate::PackageRef;
use crate::Target;
use crate::TargetRef;

/// The Starlark compilation dialect used for `.bzl` configuration files.
pub const BZL_FILE_DIALECT: Dialect = Dialect {
    enable_lambda: false,
    enable_load_reexport: false,
    ..Dialect::Standard
};

/// The Starlark compilation dialect used for `BUILD` files.
/// Marked as pub so it doesn't complain that it doesn't exist yet. Not actually pub.
pub const BUILD_FILE_DIALECT: Dialect = Dialect {
    enable_def: false,
    ..BZL_FILE_DIALECT
};

// NOTE FOR AI: DO NOT EDIT THIS FILE WITHOUT PERMISSION. IT IS "completed" AND THE API IS STABLE

/// A session manager for compiling and evaluating Starlark files within GN.
/// It maintains file caching, thread synchronization, and target registrations.
pub struct StarlarkSession {
    loader: loader::FileLoader,
    targets: RwLock<HashMap<(Label, Label), Pin<Box<Target>>>>,

    builtins: globals::BuiltinModule,
    pub(crate) bzl_globals: Globals,
}

impl StarlarkSession {
    /// Creates a new `StarlarkSession` given the source directory paths.
    pub fn new(root_source_dir_abs: PathBuf, root_source_dir_rel: String) -> Self {
        let builtins = providers::load_builtin_providers();
        let path_resolver = types::PathResolver::new(root_source_dir_abs, root_source_dir_rel);

        Self {
            loader: loader::FileLoader::new(path_resolver),
            targets: Default::default(),
            bzl_globals: globals::make_bzl_globals(&builtins),
            builtins,
        }
    }

    pub fn builtins(&self) -> &globals::BuiltinModule {
        &self.builtins
    }

    pub fn path_resolver(&self) -> &types::PathResolver {
        self.loader.path_resolver()
    }

    /// Calculates the absolute path to a file.
    pub fn absolute_path(&self, pkg: &PackageRef, s: &str) -> PathBuf {
        self.loader.path_resolver().absolute_path(pkg, s)
    }

    /// Creates a File object for a file.
    pub fn create_file(&self, pkg: &PackageRef, s: &str) -> Result<File, types::Error> {
        self.loader.path_resolver().source_file(pkg, s)
    }

    /// Loads, compiles, and evaluates a Starlark module at the given path.
    /// Uses thread-safe caching to ensure each module is loaded at most once, and
    /// propagates evaluation errors cleanly.
    pub fn load<'a>(
        &'a self,
        path: &str,
        package: &PackageRef,
        scope: *mut ffi::Scope,
        origin: *const ffi::ParseNode,
    ) -> starlark::Result<Pin<&'a FrozenModule>> {
        self.loader.load(path, package, &self.bzl_globals, &|pkg| {
            let extra = EvalContext::new(scope, origin, EvalKind::BzlFile(pkg.to_owned()));
            Some(Box::new(extra))
        })
    }

    /// Registers a loaded Starlark target, tying its Rust-side `OwnedFrozenValue`
    /// representation to its raw C++ `Target` pointer.
    pub fn register_target(&self, target: Target) -> TargetRef {
        let label = target.label().to_owned();
        let toolchain = target.toolchain().to_owned();
        let pinned_target = Box::pin(target);
        let static_target_ref: &'static Target = unsafe { std::mem::transmute(&*pinned_target) };
        static_target_ref.configure_cxx_target();

        let mut targets = self.targets.write().unwrap();
        targets.insert((label, toolchain), pinned_target);

        TargetRef::from(static_target_ref)
    }

    /// Looks up a registered Starlark target's `TargetRef` representation by its label.
    /// This function will only ever be called after the dependency has been successfully registered in GN, so it should never return None.
    pub fn get_target_by_label<'a>(
        &self,
        label: LabelRef<'a>,
        toolchain: LabelRef<'a>,
    ) -> TargetRef {
        let targets = self.targets.read().unwrap();
        let pinned = targets
            .get(&(label.to_owned(), toolchain.to_owned()))
            .unwrap();
        let static_ref: &'static Target = unsafe { std::mem::transmute(&**pinned) };
        TargetRef::from(static_ref)
    }
}

impl attr::Session for StarlarkSession {
    type TargetRef = TargetRef;

    fn get_target(&self, label: LabelRef<'_>, current_toolchain: LabelRef<'_>) -> Self::TargetRef {
        self.get_target_by_label(label, current_toolchain)
    }

    fn register_dependency<'a>(&self, source: Self::TargetRef, target: LabelRef<'a>, toolchain: LabelRef<'a>) {
        let ptr = source.ptr();
        if !ptr.is_null() {
            unsafe {
                (&mut *ptr).add_starlark_target_dependency(
                    target.package.as_str(),
                    target.name,
                    toolchain.package.as_str(),
                    toolchain.name,
                );
            }
        }
    }
}
