[package]
name = "gn_starlark"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

# LINT.IfChange
[dependencies]
starlark = "0.14.0"
starlark_derive = "0.14.0"
anyhow = "1.0"
thiserror = "1.0"
cxx = "1.0"
allocative = "0.3"
autocxx = "0.30.0"
either = "1.16.0"

[build-dependencies]
autocxx-build = "0.30.0"
bindgen = "0.69"
cxx-build = "1.0"

# RUST_DEPS needs to be kept in sync with this
# LINT.ThenChange(build/gen.py)

# In debug mode, we still optimize our dependencies.
# Otherwise our static library for this package is
# ~400MB and our link times go through the roof.
# This significantly improves link performance.
[profile.dev.package."*"]
opt-level = 3
debug = false

# Always build the code generator in release mode.
[profile.dev.build-override]
opt-level = 3

[patch.crates-io]
starlark = { path = "/usr/local/google/home/msta/starlark-rs/starlark" }
starlark_derive = { path = "/usr/local/google/home/msta/starlark-rs/starlark_derive" }
allocative = { path = "/usr/local/google/home/msta/starlark-rs/allocative/allocative" }
allocative_derive = { path = "/usr/local/google/home/msta/starlark-rs/allocative/allocative_derive" }
