[package]
name = "providers"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]

[dependencies]
allocative = { workspace = true }
starlark = { workspace = true }
starlark_derive = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
testutils = { path = "../testutils" }
