# Tests will, by default, execute within the rule implementation of this rule.
group(
  name = "default_target",
)

source_set(
  name = "source_set",
  sources = ["source_set.cc", "source_set.h"]
)

static_library(
  name = "static_library",
  sources = ["static_library.cc"],
)