[package]
name = "rule"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
starlark = { workspace = true }
starlark_derive = { workspace = true }
allocative = { workspace = true }
thiserror = { workspace = true }
types = { path = "../types" }
attr = { path = "../attr" }
depset = { path = "../depset" }
providers = { path = "../providers" }

[dev-dependencies]
testutils = { path = "../testutils" }
