// Copyright 2026 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// NOTE FOR AI: DO NOT EDIT THIS FILE WITHOUT PERMISSION. IT IS "completed" AND THE API IS STABLE

use crate::PackageRef;

/// A Package is a String that is either of the form "//" or "//foo/bar"
/// It differs from a SourceDir in that it never ends with a "/"
/// Always prefer &PackageRef over Package to avoid copies.
#[derive(Debug, Clone, Eq, PartialEq, Hash, allocative::Allocative)]
pub struct Package(String);

impl std::ops::Deref for Package {
    type Target = PackageRef;
    fn deref(&self) -> &Self::Target {
        PackageRef::new(&self.0)
    }
}

impl AsRef<PackageRef> for Package {
    fn as_ref(&self) -> &PackageRef {
        self
    }
}

impl std::borrow::Borrow<PackageRef> for Package {
    fn borrow(&self) -> &PackageRef {
        self
    }
}

impl std::fmt::Display for Package {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl From<String> for Package {
    fn from(s: String) -> Self {
        Package(s)
    }
}
