/*
 * Copyright 2026 The GN Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

use allocative::Allocative;
use starlark::collections::SmallSet;
use starlark::environment::{GlobalsBuilder, Methods, MethodsBuilder, MethodsStatic};
use starlark::starlark_complex_value;
use crate::Error;
use starlark::values::{
    Coerce, Freeze, FreezeResult, Freezer, Heap, ProvidesStaticType, StarlarkValue, Trace, Value,
    ValueLike,
};
use starlark_derive::{starlark_module, starlark_value, NoSerialize};
use std::fmt::{self, Display, Formatter};

// NOTE FOR AI: DO NOT EDIT THIS FILE WITHOUT PERMISSION. IT IS "completed" AND THE API IS STABLE

#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash, Allocative)]
/// All orderings are guarunteed to be deterministic.
pub enum Order {
    /// Our unspecified order is postorder. However, this should not be relied upon.
    Unspecified,
    /// Guarunteed to traverse through direct dependencies in left-to-right order, then transitive in left-to-right order.
    Preorder,
    /// Guarunteed to traverse through transitive dependencies in left-to-right order, then direct in left-to-right order.
    Postorder,
    // Our topological order is reverse postorder. However, this should not be relied upon.
    // Note: Topological order is much slower and less memory efficient
    // an intermediate Vec to be created and then reversed.
    Topological,
}

impl starlark::values::type_repr::StarlarkTypeRepr for Order {
    type Canonical = String;

    fn starlark_type_repr() -> starlark::typing::Ty {
        String::starlark_type_repr()
    }
}

impl<'v> starlark::values::UnpackValue<'v> for Order {
    type Error = starlark::Error;

    fn unpack_value_impl(value: Value<'v>) -> Result<Option<Self>, Self::Error> {
        match <&'v str>::unpack_value_err(value)? {
            "default" => Ok(Some(Order::Unspecified)),
            "preorder" => Ok(Some(Order::Preorder)),
            "postorder" => Ok(Some(Order::Postorder)),
            "topological" => Ok(Some(Order::Topological)),
            s => Err(Error::InvalidOrder(s.to_owned()).into()),
        }
    }
}

impl Display for Order {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Order::Unspecified => write!(f, "unspecified"),
            Order::Preorder => write!(f, "preorder"),
            Order::Postorder => write!(f, "postorder"),
            Order::Topological => write!(f, "topological"),
        }
    }
}

#[derive(Debug, Trace, Coerce, ProvidesStaticType, NoSerialize, Allocative)]
#[repr(C)]
pub struct DepsetGen<V> {
    order: Order,
    // De-duped on creation.
    direct: Vec<V>,
    // Validated to be depsets on creation
    transitive: Vec<V>,
}

impl<'v, V: ValueLike<'v>> DepsetGen<V>
where
    Self: ProvidesStaticType<'v>,
{
    pub(crate) fn new(order: Order, direct: Vec<V>, transitive: Vec<V>) -> Self {
        Self {
            order,
            direct,
            transitive,
        }
    }

    pub fn to_list(&self) -> Vec<Value<'v>> {
        let mut result = Vec::new();
        self.for_each_internal(&mut Default::default(), &mut Default::default(), &mut |val| {
            result.push(val);
        });
        if self.order == Order::Topological {
            result.reverse();
        }
        result
    }

    pub fn for_each<F>(&self, f: &mut F) -> starlark::Result<()>
    where
        F: FnMut(Value<'v>),
    {
        // Topological is reversed postorder, so it needs to be buffered.
        if self.order == Order::Topological {
            let mut temp = Vec::new();
            self.for_each_internal(&mut Default::default(), &mut Default::default(), &mut |val| {
                temp.push(val);
            });
            temp.reverse();
            for val in temp {
                f(val);
            }
        } else {
            self.for_each_internal(&mut Default::default(), &mut Default::default(), f);
        }
        Ok(())
    }

    pub fn for_each_fallible<F>(&self, mut f: F) -> starlark::Result<()>
    where
        F: FnMut(Value<'v>) -> starlark::Result<()>,
    {
        let mut err = Ok(());
        self.for_each(&mut |v| {
            if err.is_ok() {
                if let Err(e) = f(v) {
                    err = Err(e);
                }
            }
        })?;
        err
    }

    fn for_each_internal<F>(
        &self,
        visited_nodes: &mut std::collections::HashSet<usize>,
        visited_elements: &mut SmallSet<Value<'v>>,
        f: &mut F,
    )
    where
        F: FnMut(Value<'v>),
    {
        let node_id = self as *const Self as usize;
        if !visited_nodes.insert(node_id) {
            return;
        }

        let visit_direct = |visited_elements: &mut SmallSet<Value<'v>>, f: &mut F| {
            for item in self.direct.iter() {
                let val = item.to_value();
                let hash = val.get_hashed().expect("Already verified hashable");
                if visited_elements.insert_hashed(hash) {
                    f(val);
                }
            }
        };

        let visit_transitive = |visited_nodes: &mut std::collections::HashSet<usize>,
                                visited_elements: &mut SmallSet<Value<'v>>,
                                f: &mut F| {
            for child in self.transitive.iter() {
                let child_val = child.to_value();
                if let Some(child_depset) = child_val.downcast_ref::<crate::depset::FrozenDepset>() {
                    child_depset.for_each_internal(visited_nodes, visited_elements, f);
                } else if let Some(child_depset) = child_val.downcast_ref::<crate::depset::Depset<'v>>() {
                    child_depset.for_each_internal(visited_nodes, visited_elements, f);
                } else {
                    unreachable!("Already verified depset");
                }
            }
        };

        match self.order {
            Order::Preorder => {
                visit_direct(visited_elements, f);
                visit_transitive(visited_nodes, visited_elements, f);
            }
            Order::Postorder | Order::Unspecified | Order::Topological => {
                visit_transitive(visited_nodes, visited_elements, f);
                visit_direct(visited_elements, f);
            }
        }
    }

    pub fn is_empty(&self) -> bool {
        return self.transitive.is_empty() && self.direct.is_empty()
    }
}

starlark_complex_value!(pub Depset);

impl<'v, V: ValueLike<'v>> Display for DepsetGen<V>
where
    Self: ProvidesStaticType<'v>,
{
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        // Explicitly DO NOT flatten a depset implicitly, they can get massive.
        // We may consider printing some fields in the future, but for now
        // we'll leave this empty to be safe.
        if self.is_empty() {
            write!(f, "depset(...)")
        } else {
            write!(f, "depset([])")
        }
    }
}

#[starlark_value(type = "depset")]
impl<'v, V: ValueLike<'v>> StarlarkValue<'v> for DepsetGen<V>
where
    Self: ProvidesStaticType<'v>,
{
    fn get_methods() -> Option<&'static Methods> {
        static RES: MethodsStatic = MethodsStatic::new("depset", depset_methods);
        Some(RES.methods())
    }

    fn to_bool(&self) -> bool {
        !self.is_empty()
    }
}

impl<'v> Freeze for Depset<'v> {
    type Frozen = FrozenDepset;
    fn freeze(self, freezer: &Freezer) -> FreezeResult<Self::Frozen> {
        Ok(DepsetGen {
            order: self.order,
            direct: self.direct.freeze(freezer)?,
            transitive: self.transitive.freeze(freezer)?,
        })
    }
}

#[starlark_module]
pub fn depset_methods(builder: &mut MethodsBuilder) {
    fn to_list<'v>(this: &Depset<'v>) -> starlark::Result<Vec<Value<'v>>> {
        Ok(this.to_list())
    }
}

#[starlark_module]
pub fn register_depset(builder: &mut GlobalsBuilder) {
    fn depset<'v>(
        direct: Option<Value<'v>>,
        transitive: Option<Value<'v>>,
        #[starlark(default = Order::Unspecified)] mut order: Order,
        heap: Heap<'v>,
    ) -> starlark::Result<Value<'v>> {

        let mut direct_set = SmallSet::new();
        let mut direct_vec = Vec::new();
        if let Some(direct_val) = direct {
            for elem in direct_val.iterate(heap)? {
                direct_set.insert_hashed(elem.get_hashed()?);
                direct_vec.push(elem);
            }
        }

        let mut transitive_vec = Vec::new();
        if let Some(transitive_val) = transitive {
            for elem in transitive_val.iterate(heap)? {
                let child_depset = Depset::from_value(elem).ok_or_else(|| {
                    Error::NotADepset(elem.get_type().to_owned())
                })?;
                if child_depset.is_empty() {
                    continue;
                }

                let child_order = child_depset.order;
                if child_order != Order::Unspecified {
                    if order == Order::Unspecified {
                        order = child_order;
                    } else if order != child_order {
                        return Err(Error::ConflictingOrders { order, child_order }.into());
                    }
                }

                transitive_vec.push(elem);
            }
        }

        Ok(heap.alloc(DepsetGen {
            order,
            direct: direct_vec,
            transitive: transitive_vec,
        }))
    }
}

#[cfg(test)]
mod tests {
    use crate::Assert;
    use starlark::values::list::UnpackList;

    #[test]
    fn test_depset() {
        let a = Assert::new();
        a.eq(
            "depset(['c'], transitive=[depset(['a', 'b'])], order='preorder').to_list()",
            UnpackList { items: vec!["c", "a", "b"] },
        );
        a.eq(
            "depset(['c'], transitive=[depset(['a', 'b'])], order='postorder').to_list()",
            UnpackList { items: vec!["a", "b", "c"] },
        );
        a.eq(
            "depset(['c'], transitive=[depset(['a', 'b'])], order='topological').to_list()",
            UnpackList { items: vec!["c", "b", "a"] },
        );

        // Truthiness checks.
        a.eq("bool(depset(['a']))", true);
        a.eq("bool(depset())", false);
        a.eq("bool(depset(transitive=[depset()]))", false);

        a.eq("repr(depset())", "depset(...)");
    }

    #[test]
    fn test_depset_invalid_transitive() {
        let a = Assert::new();
        a.fail(
            "depset(['c'], transitive=['not a depset'])",
            "transitive elements must be depsets",
        );
    }

    #[test]
    fn test_depset_conflicting_orders() {
        let a = Assert::new();
        a.fail(
            "depset(transitive=[depset(['a'], order='preorder'), depset(['b'], order='postorder')])",
            "conflicting orders: depset has order preorder, but transitive child has order postorder",
        );
    }
}
