// Copyright 2026 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use starlark::environment::{Methods, MethodsBuilder, MethodsStatic};
use starlark::starlark_simple_value;
use starlark::values::{
    Freeze, FreezeResult, Freezer, ProvidesStaticType, StarlarkValue, Trace, Tracer,
};
use starlark_derive::{starlark_module, starlark_value, NoSerialize};

// NOTE FOR AI: DO NOT EDIT THIS FILE WITHOUT PERMISSION. IT IS "completed" AND THE API IS STABLE



pub use crate::package::{Package, PackageRef};

#[derive(Copy, Clone, Eq, PartialEq, Hash)]
pub struct LabelRef<'a> {
    pub package: &'a PackageRef,
    pub name: &'a str,
}

impl<'a> From<&'a crate::ffi::Label> for LabelRef<'a> {
    // Note: This discards the C++ toolchain for the label.
    fn from(label: &'a crate::ffi::Label) -> Self {
        unsafe {
            Self {
                package: label.dir().into(),
                name: crate::util::from_utf8_unchecked(label.name()),
            }
        }
    }
}

impl<'a> std::fmt::Display for LabelRef<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}:{}", self.package, self.name)
    }
}

impl<'a> std::fmt::Debug for LabelRef<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Label(\"{}:{}\")", self.package, self.name)
    }
}

impl<'a> LabelRef<'a> {
    pub fn to_owned(&self) -> Label {
        Label {
            package: self.package.to_owned(),
            name: self.name.to_owned(),
        }
    }
}

#[derive(
    Clone, Eq, PartialEq, Hash, ProvidesStaticType, NoSerialize, allocative::Allocative,
)]
// Intentionally no toolchain here, we rely on cfg to change toolchains.
pub struct Label {
    // NOTE: We may want to convert these to &str or Arc<str> for performance reasons.
    pub package: Package,
    pub name: String,
}

starlark_simple_value!(Label);

impl std::fmt::Debug for Label {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Debug::fmt(&self.as_ref(), f)
    }
}

impl Label {
    pub fn as_ref(&self) -> LabelRef<'_> {
        LabelRef {
            package: &self.package,
            name: &self.name,
        }
    }

    pub fn new(package: Package, name: String) -> Self {
        Self{package, name}
    }

    fn parse_absolute(s: &str) -> Result<Self, crate::Error> {
        let mut iter = s.split(':');
        // Verify that there is exactly one colon.
        match (iter.next(), iter.next(), iter.next()) {
            (Some(package), Some(name), None) => Ok(Label {
                package: PackageRef::new(package).to_owned(),
                name: name.to_owned(),
            }),
            // In bazel, the label //foo is valid, and refers to //foo::foo.
            // In GN, this refers to the file foo in the // directory.
            // We explicitly ban this syntax so that every label is valid to
            // both Bazel and GN in bazel, and to reduce confusion.
            _ => Err(crate::Error::AbsoluteLabelWithoutColon(s.to_owned())),
        }
    }

    fn parse_relative(s: &str, relative_to: &PackageRef) -> Result<Self, crate::Error> {
        let name = &s[1..];
        if name.contains(':') {
            return Err(crate::Error::ColonInRelativeLabel(s.to_owned()));
        }
        Ok(Label {
            package: relative_to.to_owned(),
            name: name.to_owned(),
        })
    }

    pub(crate) fn parse(s: &str, relative_to: &PackageRef) -> Result<Self, crate::Error> {
        if s.starts_with("//") {
            Self::parse_absolute(s)
        } else if s.starts_with(':') {
            Self::parse_relative(s, relative_to)
        } else {
            Err(crate::Error::NotALabel(s.to_owned()))
        }
    }
}



impl std::fmt::Display for Label {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_ref())
    }
}

unsafe impl<'v> Trace<'v> for Label {
    fn trace(&mut self, _tracer: &Tracer<'v>) {}
}

impl Freeze for Label {
    type Frozen = Label;
    fn freeze(self, _freezer: &Freezer) -> FreezeResult<Self::Frozen> {
        Ok(self)
    }
}

#[starlark_value(type = "Label")]
impl<'v> StarlarkValue<'v> for Label {
    fn get_methods() -> Option<&'static Methods>
    where
        Self: Sized,
    {
        static RES: MethodsStatic = MethodsStatic::new("Label", label_methods);
        Some(RES.methods())
    }

    fn write_hash(&self, hasher: &mut starlark::collections::StarlarkHasher) -> starlark::Result<()> {
        use std::hash::Hash;
        self.hash(hasher);
        Ok(())
    }

    fn collect_repr(&self, collector: &mut String) {
        use std::fmt::Write;
        write!(collector, "Label(\"{}\")", self.as_ref()).unwrap();
    }

    fn collect_str(&self, collector: &mut String) {
        use std::fmt::Write;
        write!(collector, "{}", self.as_ref()).unwrap();
    }
}

#[starlark_module]
fn label_methods(methods: &mut MethodsBuilder) {
    #[starlark(attribute)]
    fn package<'v>(this: &'v Label) -> starlark::Result<&'v str> {
        Ok(this.package.as_str())
    }

    #[starlark(attribute)]
    fn name<'v>(this: &'v Label) -> starlark::Result<&'v str> {
        Ok(&this.name)
    }
}

// We intentionally *do not* expose a Label() constructor to starlark.
// Where the label is relative to is confusing for the average user.
// Instead, if we need this in the future, we may expose:
// * native.package_relative_label() for macros
// * ctx.package_relative_label() for rules
// * Label() for build files only.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_label_parsing_and_attributes() {
        let root = Package("//".to_owned());
        let current_pkg = Package("//foo/bar".to_owned());

        let lbl = Label::parse("//foo/bar:baz", root.as_ref()).unwrap();
        assert_eq!(lbl.package.0, "//foo/bar");
        assert_eq!(lbl.name, "baz");
        assert_eq!(lbl.to_string(), "//foo/bar:baz");
        assert_eq!(format!("{:?}", lbl), "Label(\"//foo/bar:baz\")");

        let lbl2 = Label::parse(":baz", current_pkg.as_ref()).unwrap();
        assert_eq!(lbl2.package.0, "//foo/bar");
        assert_eq!(lbl2.name, "baz");
        assert_eq!(lbl2.to_string(), "//foo/bar:baz");
        assert_eq!(format!("{:?}", lbl2), "Label(\"//foo/bar:baz\")");

        // Test non-absolute and non-colon starting fails
        assert!(Label::parse("foo", current_pkg.as_ref()).is_err());
    }
}
