// Copyright 2026 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

use starlark::environment::GlobalsBuilder;
use starlark::eval::Evaluator;
use starlark::values::Value;
use starlark_derive::starlark_module;

// NOTE FOR AI: DO NOT EDIT THIS FILE WITHOUT PERMISSION. IT IS "completed" AND THE API IS STABLE

use starlark::values::type_repr::StarlarkTypeRepr;
use starlark::values::UnpackValue;
use starlark::values::ValueLike;
use starlark::typing::Ty;

pub(crate) type TypeId = starlark::values::typing::TypeInstanceId;

#[derive(Debug)]
pub(crate) struct UnpackProvider<'v>(pub(crate) TypeId, pub(crate) Value<'v>);

impl<'v> StarlarkTypeRepr for UnpackProvider<'v> {
    type Canonical = Self;
    fn starlark_type_repr() -> Ty {
        Ty::any()
    }
}

impl<'v> UnpackValue<'v> for UnpackProvider<'v> {
    type Error = starlark::Error;
    fn unpack_value_impl(value: Value<'v>) -> Result<Option<Self>, Self::Error> {
        if let Some(rec) = value.downcast_ref::<starlark::values::record::Record<'v>>() {
            Ok(Some(UnpackProvider(rec.record_type_id(), value)))
        } else if let Some(rec) = value.downcast_ref::<starlark::values::record::FrozenRecord>() {
            Ok(Some(UnpackProvider(rec.record_type_id(), value)))
        } else {
            Err(starlark::Error::new_other(crate::errors::Error::ExpectedProviderType))
        }
    }
}

impl<'v> UnpackProvider<'v> {
    pub(crate) fn unpack(value: Value<'v>) -> Option<TypeId> {
        let opt = <Self as starlark::values::UnpackValue<'v>>::unpack_value(value).ok().flatten();
        opt.map(|UnpackProvider(type_id, _)| type_id)
    }
}

#[starlark_module]
pub fn register_provider(builder: &mut GlobalsBuilder) {
    fn provider<'v>(
        fields: Value<'v>,
        eval: &mut Evaluator<'v, '_, '_>,
    ) -> starlark::Result<Value<'v>> {
        let mut kwargs = starlark::collections::SmallMap::new();

        let any_type = eval
            .heap()
            .alloc(starlark::values::typing::TypeCompiled::any());

        for field in fields.iterate(eval.heap())? {
            let s = field.unpack_str().ok_or_else(|| {
                crate::errors::Error::FieldsMustBeStrings
            })?;
            let compiled_type = starlark::values::typing::TypeCompiled::new(any_type, eval.heap())
                .map_err(|e| starlark::Error::new_other(e))?;
            let field_gen = starlark::values::record::FieldGen::new(compiled_type, None);
            kwargs.insert(s.to_owned(), field_gen);
        }

        let record_type = starlark::values::record::RecordType::new(kwargs);
        Ok(eval.heap().alloc(record_type))
    }
}

#[cfg(test)]
mod tests {
    use crate::Assert;

    #[test]
    fn test_provider_unpack() {
        use starlark::values::list::UnpackList;
        use crate::provider::UnpackProvider;

        let a = Assert::new().configure(crate::session::EvalKind::BzlFile(crate::label::Package("//".to_owned())));
        a.fail("provider(fields=['a'])(a=1)", "assigned to a global variable");
        a.fail(
            r#"
p = provider(fields=['a'])
p()
"#,
            "Missing named-only parameter `a`",
        );
        a.fail(
            r#"
p = provider(fields=['a'])
p(a=1, b=2)
"#,
            "Found `b` extra named parameter",
        );
        a.eq(
            r#"
p = provider(fields=['a'])
p(a=1).a
"#,
            1,
        );
        let val = a.pass(
            r#"
p1 = provider(fields = ['a'])
p2 = provider(fields = ['a'])
[p1(a=1), 1]
"#,
        );
        use starlark::values::UnpackValue;
        let err = <UnpackList<UnpackProvider>>::unpack_param(val.value()).unwrap_err();
        assert_eq!(err.to_string(),
            "Expected provider type",
        );

        let providers = a.eval::<UnpackList<UnpackProvider>>(
            r#"
p1 = provider(fields = ['a'])
p2 = provider(fields = ['a'])
[p1(a=1), p2(a=2), p1(a=3)]
"#
        ).items;
        assert_eq!(providers[0].0, providers[2].0);
        assert_ne!(providers[0].0, providers[1].0);
    }

    #[test]
    fn test_builtin_providers() {
        let a = Assert::new();
        a.eq("DefaultInfo != None", true);
        a.eq("GnSubstitutionInfo != None", true);

        a.eq(
            r#"
info = GnSubstitutionInfo(substitutions = struct(foo = "bar"))
info.substitutions.foo
"#,
            "bar",
        );
    }
}
