use crate::label::{Label, LabelRef, PackageRef};
use crate::target::Target;
use crate::errors::Error;
use starlark::environment::{FrozenModule, Module};
use starlark::eval::Evaluator;
use starlark::eval::ReturnFileLoader;
use starlark::syntax::{AstModule, Dialect};
use starlark::values::FrozenHeapName;
use std::collections::hash_map::{Entry, HashMap};
use std::fs;
use std::path::PathBuf;
use std::pin::Pin;
use std::sync::{Arc, Condvar, Mutex, RwLock};

/// The Starlark compilation dialect used for `.bzl` configuration files.
pub const BZL_FILE_DIALECT: Dialect = Dialect {
    enable_lambda: false,
    enable_load_reexport: false,
    ..Dialect::Standard
};

/// The Starlark compilation dialect used for `BUILD` files.
/// Marked as pub so it doesn't complain that it doesn't exist yet. Not actually pub.
pub const BUILD_FILE_DIALECT: Dialect = Dialect {
    enable_def: false,
    ..BZL_FILE_DIALECT
};

// NOTE FOR AI: DO NOT EDIT THIS FILE WITHOUT PERMISSION. IT IS "completed" AND THE API IS STABLE


/// A session manager for compiling and evaluating Starlark files within GN.
/// It maintains file caching, thread synchronization, and target registrations.
pub struct StarlarkSession {
    /// Absolute path to the root source dir on disk.
    pub root_source_dir_abs: PathBuf,
    /// Path to the root source dir relative to the output directory.
    pub root_source_dir_rel: PathBuf,
    files: RwLock<HashMap<String, Arc<Mutex<FileStatus>>>>,
    targets: RwLock<HashMap<(Label, Label), Pin<Box<crate::target::Target>>>>,
}

enum FileStatus {
    Loading {
        // A CondVar to wait on for the filestatus to resolve to Loaded.
        // Using Arc allows us to clone it and release the mutex lock before waiting.
        wait: Arc<Condvar>,
        // What needs to finish evaluating before this can be evaluated.
        // This is used purely for cycle detection.
        needs: Option<String>,
    },
    Loaded(starlark::Result<Pin<Box<FrozenModule>>>),
}

impl Default for FileStatus {
    fn default() -> Self {
        FileStatus::Loading {
            wait: Arc::new(Condvar::new()),
            needs: None,
        }
    }
}

fn set_needs(file_status: &Arc<Mutex<FileStatus>>, value: &str) {
    let mut status = file_status.lock().unwrap();
    if let FileStatus::Loading { ref mut needs, .. } = &mut *status {
        *needs = Some(value.to_owned());
    }
}

impl StarlarkSession {
    /// Creates a new `StarlarkSession` given the source directory paths.
    pub fn new(root_source_dir_abs: PathBuf, root_source_dir_rel: PathBuf) -> Self {
        Self {
            root_source_dir_abs,
            root_source_dir_rel,
            files: Default::default(),
            targets: Default::default(),
        }
    }

    fn wait_for_load<'a>(
        &'a self,
        file_status: &Arc<Mutex<FileStatus>>,
    ) -> starlark::Result<Pin<&'a FrozenModule>> {
        let mut status = file_status.lock().unwrap();
        while let FileStatus::Loading { wait, .. } = &*status {
            let wait = wait.clone();
            status = wait.wait(status).unwrap();
        }
        self.get_loaded(&*status)
    }

    fn set_complete<'a>(
        &'a self,
        file_status: &Arc<Mutex<FileStatus>>,
        result: starlark::Result<FrozenModule>,
    ) -> starlark::Result<Pin<&'a FrozenModule>> {
        let mut status = file_status.lock().unwrap();
        if let FileStatus::Loading { wait, .. } = &*status {
            wait.notify_all();
        }
        *status = FileStatus::Loaded(result.map(Box::pin));
        self.get_loaded(&*status)
    }

    fn get_loaded<'a>(&'a self, status: &FileStatus) -> starlark::Result<Pin<&'a FrozenModule>> {
        match status {
            FileStatus::Loading { .. } => unreachable!(),
            // By design, we never overwrite entries in the file hash map, so this is safe.
            FileStatus::Loaded(Ok(m)) => Ok(unsafe { std::mem::transmute::<Pin<&FrozenModule>, Pin<&'a FrozenModule>>(m.as_ref()) }),
            // starlark::Error doesn't implement Clone, so we do a poor man's clone.
            FileStatus::Loaded(Err(e)) => Err(starlark::Error::new_other(anyhow::anyhow!("{}", e))),
        }
    }

    /// Loads, compiles, and evaluates a Starlark module at the given path.
    /// Uses thread-safe caching to ensure each module is loaded at most once, and
    /// propagates evaluation errors cleanly.
    pub fn load<'a>(
        &'a self,
        path: &str,
        package: &PackageRef,
        scope: *mut crate::ffi::Scope,
        origin: *const crate::ffi::ParseNode,
    ) -> starlark::Result<Pin<&'a FrozenModule>> {
        let label =
            Label::parse(path, package).map_err(|e| starlark::Error::new_other(e))?;
        let file_status = {
            let mut loader = self.files.write().unwrap();
            match loader.entry(path.to_owned()) {
                Entry::Occupied(entry) => {
                    let file_status = entry.get().clone();
                    drop(loader);
                    return self.wait_for_load(&file_status);
                }
                // We're about to start evaluating it.
                Entry::Vacant(entry) => entry.insert(Default::default()).clone(),
            }
        };

        // Read and parse the file to get its dependencies.
        let content =
            fs::read_to_string(label.package.abs_path(self).join(&label.name)).map_err(|_| {
                starlark::Error::from(Error::ReadFailed(label.to_string()))
            })?;
        let ast = AstModule::parse(&path, content, &BZL_FILE_DIALECT)?;

        let mut deps: Vec<(String, Pin<&FrozenModule>)> = Default::default();
        if !ast.loads().is_empty() {
            for load in ast.loads() {
                set_needs(&file_status, &load.module_id);
                if let Some(cycle) = self.find_cycle_path(&path, &load.module_id) {
                    let err = Error::CycleDetected(cycle).into();
                    return self.set_complete(&file_status, Err(err));
                }

                deps.push((
                    load.module_id.to_owned(),
                    self.load(&load.module_id, &label.package.as_ref(), scope, origin)?,
                ));
            }
        }

        let globals = crate::globals::make_globals();
        let deps_map: HashMap<&str, &FrozenModule> =
            deps.iter().map(|(k, v)| (k.as_str(), v.get_ref())).collect();
        let loader = ReturnFileLoader { modules: &deps_map };
        let module = Module::with_temp_heap(|module| {
            {
                let extra = EvalContext::new(
                    scope,
                    origin,
                    EvalKind::BzlFile(label.package.clone()),
                );
                let mut eval = Evaluator::new(&module);
                eval.extra = Some(&extra);
                eval.set_loader(&loader);
                eval.eval_module(ast, globals)?;
            }
            // After creating a module we freeze it, preventing further mutation.
            // It can now be used as the input for other Starlark modules.
            // Each frozen module is given a name to identify its heap.
            module
                .freeze_named(FrozenHeapName::User(Box::new(path.to_owned())))
                .map_err(|e| starlark::Error::new_other(e))
        });

        // TODO: We need to call setup->AddGenDependencies() to ensure that
        // when .bzl files change, it decides to rerun `gn gen`
        self.set_complete(&file_status, module)
    }

    fn find_cycle_path(&self, start: &str, target: &str) -> Option<Vec<String>> {
        let loader = self.files.read().unwrap();
        let mut cur = target.to_owned();
        let mut cycle = vec![cur.clone()];
        while let Some(status_mutex) = loader.get(&cur) {
            let status = status_mutex.lock().unwrap();
            if let FileStatus::Loading {
                needs: Some(need), ..
            } = &*status
            {
                cycle.push(need.clone());
                cur = need.clone();
            } else {
                break;
            }
            if cur == start {
                return Some(cycle);
            }
        }
        None
    }

    /// Registers a loaded Starlark target, tying its Rust-side `OwnedFrozenValue`
    /// representation to its raw C++ `Target` pointer.
    pub fn register_target(
        &self,
        target: Target,
    ) -> crate::target::TargetRef {
        let label = target.label().to_owned();
        let toolchain = target.toolchain().to_owned();
        let pinned_target = Box::pin(target);
        let static_target_ref: &'static Target = unsafe { std::mem::transmute(&*pinned_target) };

        let mut targets = self.targets.write().unwrap();
        targets.insert((label, toolchain), pinned_target);

        static_target_ref.configure_cxx_target();

        crate::target::TargetRef(static_target_ref)
    }

    /// Looks up a registered Starlark target's `TargetRef` representation by its label.
    /// This function will only ever be called after the dependency has been successfully registered in GN, so it should never return None.
    pub fn get_target_by_label<'a>(&self, label: LabelRef<'a>, toolchain: LabelRef<'a>) -> crate::target::TargetRef {
        let targets = self.targets.read().unwrap();
        let pinned = targets.get(&(label.to_owned(), toolchain.to_owned())).unwrap();
        let static_ref: &'static Target = unsafe { std::mem::transmute(&**pinned) };
        crate::target::TargetRef(static_ref)
    }
}

pub use crate::eval_context::{EvalContext, EvalKind};

#[cfg(test)]
mod tests {
    use super::*;

    pub fn run_starlark(path: &str) -> starlark::Result<FrozenModule> {
        let testdata_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata");
        let loader = StarlarkSession::new(testdata_path, "../..".into());
        let setup = crate::ffi::TestWithScope::new();
        let scope_ptr = setup.scope();
        // always load from the root dir.
        loader
            .load(&path, PackageRef::new("//"), scope_ptr, std::ptr::null())
            .map(|m| (*m).clone())
    }

    #[test]
    fn test_load_dependencies() {
        let module = run_starlark("//load:root.bzl").unwrap();
        assert_eq!(module.get("root").unwrap().unpack_i32(), Some(2));
    }

    #[test]
    fn test_cycle_detection_single_thread() {
        let res = run_starlark("//cycle:a.bzl");
        assert!(res.is_err());
        let err_msg = res.unwrap_err().to_string();
        assert!(
            err_msg.contains("cycle detected"),
            "expected cycle error, got: {}",
            err_msg
        );
    }
}
