/*
 * Copyright 2026 The GN Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

use std::fmt::{Display, Formatter};
use starlark::environment::{Methods, MethodsBuilder, MethodsStatic};
use starlark::values::{
    Freeze, FreezeResult, Freezer, Heap, ProvidesStaticType, StarlarkValue, Value,
    ValueLike, FrozenValue, FrozenHeapRef, UnpackValue,
};
use starlark::values::typing::TypeInstanceId;
use starlark::collections::SmallMap;
use starlark_derive::{starlark_module, starlark_value, NoSerialize};
use starlark::starlark_simple_value;
use crate::Error;
use crate::globals::make_builtins;
use crate::label::{Label, LabelRef, PackageRef};
use std::ptr::NonNull;
use crate::rule::FrozenRuleCallable;
use crate::provider::UnpackProvider;
use starlark::values::list::UnpackList;
use starlark::values::FrozenValueTyped;

#[derive(allocative::Allocative)]
pub struct Target {
    #[allocative(skip)]
    ptr: NonNull<crate::ffi::Target>,
    /// Set for targets generated by starlark only.
    #[allocative(skip)]
    rule: Option<FrozenValueTyped<'static, FrozenRuleCallable>>,
    attrs: starlark::collections::SmallMap<&'static str, crate::attr::Attr>,
    providers: starlark::collections::SmallMap<TypeInstanceId, FrozenValue>,
    #[allocative(skip)]
    provider_heap: FrozenHeapRef,
    #[allocative(skip)]
    custom_ninja: std::cell::UnsafeCell<Option<String>>,
    declared_outputs: Vec<std::path::PathBuf>,
}

unsafe impl Send for Target {}
unsafe impl Sync for Target {}


impl Target {
    pub fn new_starlark(
        ptr: NonNull<crate::ffi::Target>,
        rule: starlark::values::FrozenValueTyped<'static, FrozenRuleCallable>,
        attrs: starlark::collections::SmallMap<&'static str, crate::attr::Attr>,
    ) -> Self {
        Self {
            ptr,
            rule: Some(rule),
            attrs,
            providers: starlark::collections::SmallMap::new(),
            provider_heap: Default::default(),
            custom_ninja: std::cell::UnsafeCell::new(None),
            declared_outputs: Default::default(),
        }
    }

    pub fn new_cxx(
        ptr: NonNull<crate::ffi::Target>,
    ) -> Self {
        // Create a frozen heap containing the DefaultInfo object.
        let (providers, provider_heap) = starlark::environment::Module::with_temp_heap(|module| -> Result<_, starlark::Error> {
            let heap = module.heap();
            let builtins = crate::globals::make_builtins();
            use crate::ffi::rust_types::ToRust;

            let files = unsafe { crate::ffi::GetTargetOutputFiles(ptr.as_ref()) }
                .iter()
                .map(|out| heap.alloc(out.to_rust()))
                .collect::<Vec<_>>();

            let default_info_inst = heap.alloc_complex(starlark::values::record::Record {
                typ: builtins.default_info.to_value(),
                values: vec![
                    Value::new_none(),
                    heap.alloc(crate::depset::Depset::new(
                        crate::depset::Order::Unspecified,
                        files,
                        Vec::new(),
                    )),
                ]
                .into_boxed_slice(),
            });

            module.set("", default_info_inst);

            let frozen_module = module
                .freeze()
                .map_err(|e| Error::FreezeFailed(format!("{:?}", e)))?;

            Ok((
                std::iter::once((
                    builtins.default_info_type,
                    frozen_module
                        .get("")?
                        .value()
                        .unpack_frozen()
                        .unwrap(),
                ))
                .collect::<SmallMap<_, _>>(),
                frozen_module.frozen_heap().clone(),
            ))
        }).unwrap();

        Self {
            ptr,
            rule: None,
            attrs: starlark::collections::SmallMap::new(),
            providers,
            provider_heap,
            custom_ninja: std::cell::UnsafeCell::new(None),
            declared_outputs: Default::default(),
        }
    }

    pub fn package<'a>(&'a self) -> &'a PackageRef {
        unsafe { crate::ffi::GetTargetLabel(self.ptr.as_ref()) }.dir().into()
    }

    pub fn label<'a>(&'a self) -> LabelRef<'a> {
        unsafe { crate::ffi::GetTargetLabel(self.ptr.as_ref()) }.into()
    }

    pub fn toolchain<'a>(&'a self) -> LabelRef<'a> {
        let label = unsafe { crate::ffi::GetTargetLabel(self.ptr.as_ref()) };
        LabelRef {
            package: label.toolchain_dir().into(),
            name: unsafe { crate::util::from_utf8_unchecked(label.toolchain_name()) },
        }
    }

    pub fn outputs(&self) -> Vec<crate::file::File> {
        use crate::ffi::ToRust;
        let outputs_cxx = unsafe { crate::ffi::GetTargetOutputFiles(self.ptr.as_ref()) };
        outputs_cxx.iter().map(|out| out.to_rust()).collect()
    }

    pub(crate) fn ptr(&self) -> *mut crate::ffi::Target {
        self.ptr.as_ptr()
    }

    pub(crate) fn configure_cxx_target(&self) {
        unsafe {
            crate::ffi::SetTargetStarlarkTarget(
                self.ptr(),
                self as *const Target as *mut Target as *mut crate::ffi::bindings::rust::RustTarget,
            );
        }
    }

    pub(crate) fn rule(&self) -> Option<FrozenValueTyped<'static, FrozenRuleCallable>> {
        self.rule
    }

    pub(crate) fn get_unevaluated_attrs(&self) -> &starlark::collections::SmallMap<&'static str, crate::attr::Attr> {
        &self.attrs
    }

    pub(crate) fn set_providers<'v>(&mut self, providers: Value<'v>) -> Result<(), starlark::Error> {
        let builtins = make_builtins();
        let (providers, provider_heap) = if providers.is_none() {
            (SmallMap::new(), Default::default())
        } else {
            starlark::environment::Module::with_temp_heap(|module| -> Result<_, starlark::Error> {
                // Safety: We know that the value lives at least as long as this
                // function, so extending its lifetime is ok.
                let providers_list = module.heap().alloc(unsafe {
                    std::mem::transmute::<Value<'v>, Value>(providers)
                });
                module.set("", providers_list);

                let frozen_module = module
                    .freeze()
                    .map_err(|e| Error::FreezeFailed(format!("{:?}", e)))?;

                Ok((
                    UnpackList::<UnpackProvider>::unpack_value_err(
                        frozen_module
                            .get("")?
                            .value(),
                    )?
                    .items
                    .into_iter()
                    .map(|UnpackProvider(k, v)| (k, v.unpack_frozen().unwrap()))
                    .collect::<SmallMap<_, _>>(),
                    frozen_module.frozen_heap().clone(),
                ))
            })?
        };

        self.providers = providers;
        self.providers.entry(builtins.default_info_type).or_insert(builtins.empty_default_info);
        self.provider_heap = provider_heap;
        Ok(())
    }

    pub(crate) fn get_custom_ninja_ref(&self) -> Option<&String> {
        unsafe { (*self.custom_ninja.get()).as_ref() }
    }

    pub(crate) fn set_custom_ninja(&self, val: String) {
        unsafe { *self.custom_ninja.get() = Some(val); }
    }

    pub(crate) fn add_declared_output(&mut self, path: std::path::PathBuf) {
        self.declared_outputs.push(path);
    }
}

impl std::fmt::Debug for Target
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Target({}, {:?})", self.label(), self.ptr)
    }
}

impl Display for Target
{
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.label())
    }
}

#[derive(Copy, Clone, Debug, ProvidesStaticType, NoSerialize, allocative::Allocative)]

pub struct TargetRef(pub(crate) &'static Target);

starlark_simple_value!(TargetRef);

impl std::fmt::Display for TargetRef {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(self.0, f)
    }
}

unsafe impl<'v> starlark::values::Trace<'v> for TargetRef {
    fn trace(&mut self, _tracer: &starlark::values::Tracer<'v>) {}
}

impl std::ops::Deref for TargetRef {
    type Target = Target;
    fn deref(&self) -> &Self::Target {
        self.0
    }
}

impl Freeze for TargetRef {
    type Frozen = TargetRef;
    fn freeze(self, _freezer: &Freezer) -> FreezeResult<Self::Frozen> {
        Err(starlark::values::FreezeError::new(
            crate::errors::Error::CannotFreezeTarget.to_string(),
        ))
    }
}

#[starlark_module]
fn target_methods(methods: &mut MethodsBuilder) {
    #[starlark(attribute)]
    fn label(this: &TargetRef) -> starlark::Result<Label> {
        Ok(this.label().to_owned())
    }
}

#[starlark_value(type = "Target")]
impl<'v> StarlarkValue<'v> for TargetRef
{
    fn get_methods() -> Option<&'static Methods>
    where
        Self: Sized,
    {
        static RES: MethodsStatic = MethodsStatic::new("Target", target_methods);
        Some(RES.methods())
    }

    fn at(&self, index: Value<'v>, heap: Heap<'v>) -> starlark::Result<Value<'v>> {
        let type_id = if let Some(rt) = index.downcast_ref::<starlark::values::record::RecordType<'v>>() {
            rt.type_id()
        } else if let Some(rt) = index.downcast_ref::<starlark::values::record::FrozenRecordType>() {
            rt.type_id()
        } else {
            return Err(Error::ExpectedProviderType.into());
        };

        if let Some(owned) = self.providers.get(&type_id) {
            heap.add_reference(&self.provider_heap);
            Ok(Value::new_frozen(*owned))
        } else {
            Ok(Value::new_none())
        }
    }

    fn is_in(&self, other: Value<'v>) -> starlark::Result<bool> {
        let type_id = if let Some(rt) = other.downcast_ref::<starlark::values::record::RecordType<'v>>() {
            rt.type_id()
        } else if let Some(rt) = other.downcast_ref::<starlark::values::record::FrozenRecordType>() {
            rt.type_id()
        } else {
            return Ok(false);
        };
        Ok(self.providers.contains_key(&type_id))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use starlark::environment::Module;
    use starlark::eval::Evaluator;
    use starlark::syntax::{AstModule, Dialect};
    use std::path::PathBuf;

    #[test]
    fn test_target_in_operator() {
        let setup = crate::ffi::TestWithScope::new();
        let scope_ptr = setup.scope();

        let out = crate::ffi::Value::new();
        autocxx::prelude::moveit!(let mut out_pin = out);
        unsafe {
            crate::ffi::InitializeTargetScope(
                out_pin.as_mut(),
                scope_ptr,
            );
        }

        let err_ctor = crate::ffi::Err::new();
        autocxx::prelude::moveit!(let mut err = err_ctor);
        let target_ptr = unsafe {
            crate::ffi::CreateTarget(
                "".into(),
                "my_target".into(),
                std::ptr::null(),
                out_pin.as_mut(),
                err.as_mut().get_mut() as *mut crate::ffi::Err,
            )
        };
        assert!(!target_ptr.is_null());

        let rust_target = crate::target::Target::new_cxx(std::ptr::NonNull::new(target_ptr).unwrap());
        let session = crate::session::StarlarkSession::new(PathBuf::new(), PathBuf::new());
        let target_ref: TargetRef = session.register_target(rust_target);

        Module::with_temp_heap(|module| {
            let mut eval = Evaluator::new(&module);
            let dialect = Dialect::Extended;

            let builtins = crate::globals::make_builtins();
            module.set("DefaultInfo", builtins.default_info.to_value());
            module.set("my_target", module.heap().alloc(target_ref));

            let globals = crate::globals::make_globals();

            let ast1 = AstModule::parse("test.bzl", "res1 = DefaultInfo in my_target".to_owned(), &dialect).unwrap();
            eval.eval_module(ast1, &globals).unwrap();
            let res = module.get("res1").unwrap();
            assert_eq!(res.unpack_bool(), Some(true));

            let other_prov_expr = r#"
MyProvider = provider(fields = [])
res2 = MyProvider in my_target
"#;
            let ast2 = AstModule::parse("test.bzl", other_prov_expr.to_owned(), &dialect).unwrap();
            eval.eval_module(ast2, &globals).unwrap();
            let res2 = module.get("res2").unwrap();
            assert_eq!(res2.unpack_bool(), Some(false));

            let ast3 = AstModule::parse("test.bzl", "res3 = 'not_a_provider' in my_target".to_owned(), &dialect).unwrap();
            eval.eval_module(ast3, &globals).unwrap();
            let res3 = module.get("res3").unwrap();
            assert_eq!(res3.unpack_bool(), Some(false));
        });
    }
}