[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
starlark = { workspace = true }
starlark_derive = { workspace = true }
cxx = { workspace = true }
types = { path = "../types" }
thiserror = { workspace = true }
allocative = { workspace = true }
loader = { path = "../loader" }
depset = { path = "../depset" }
rule = { path = "../rule" }
providers = { path = "../providers" }
anyhow = { workspace = true }
attr = { path = "../attr" }
